[tools]
deno = "2.9.7"
"github:bokwoon95/wgo" = "v0.7.1"
"github:pressly/goose" = "v3.28.0"
go = "1.25"
gofumpt = "v0.12.0"
golangci-lint = "v2.13.2"

[tasks.gofumpt]
description = "Format Go code using gofumpt"
run = "gofumpt -w ."

[tasks.lint]
description = "Lint Go code using golangci-lint"
run = "golangci-lint run"

[tasks.check]
description = "Run all formatting and linting tasks"
depends = ["gofumpt", "lint"]

[tasks.vendor]
description = "Download vendored frontend libraries"
run = """
curl -sLo assets/static/js/flatpickr.min.js https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/flatpickr.min.js
curl -sLo assets/static/css/flatpickr.min.css https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/flatpickr.min.css
curl -sLo assets/static/js/fumsV3.min.js https://pkg.api.bible/fumsV3.min.js
"""

[tasks.dev]
description = "Start the development server with live reload"
run = """
if ! pgrep -f "wgo run .* ./cmd/server" > /dev/null; then
    echo "Server is already running."
    exit 0
fi

echo "Starting server..."
CGO_ENABLED=1 wgo run -file .go -file .css -file .html -file .gotmpl -file .js ./cmd/server
"""

